$(document).ready(function(){
	$('.btn-menu').click(function(){
		$('#menu-mobile').toggleClass('nyala');
		$('.brand').toggleClass('nyalabrand');
		$('#side-nav').toggleClass('nyalaside');
		$('span').toggleClass('nyala2');
		$('span').toggleClass('nyala3');
		$('span').toggleClass('nyala4');
	});
});
